<!DOCTYPE html>
<!-- saved from url=(0014)about:internet -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=9" >

<title>Practical Machine Learning - Course Project</title>

<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 12px;
   margin: 8px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 { 
   font-size:2.2em; 
}

h2 { 
   font-size:1.8em; 
}

h3 { 
   font-size:1.4em; 
}

h4 { 
   font-size:1.0em; 
}

h5 { 
   font-size:0.9em; 
}

h6 { 
   font-size:0.8em; 
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre {	
   margin-top: 0;
   max-width: 95%;
   border: 1px solid #ccc;
   white-space: pre-wrap;
}

pre code {
   display: block; padding: 0.5em;
}

code.r, code.cpp {
   background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * { 
      background: transparent !important; 
      color: black !important; 
      filter:none !important; 
      -ms-filter: none !important; 
   }

   body { 
      font-size:12pt; 
      max-width:100%; 
   }
       
   a, a:visited { 
      text-decoration: underline; 
   }

   hr { 
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote { 
      padding-right: 1em; 
      page-break-inside: avoid; 
   }

   tr, img { 
      page-break-inside: avoid; 
   }

   img { 
      max-width: 100% !important; 
   }

   @page :left { 
      margin: 15mm 20mm 15mm 10mm; 
   }
     
   @page :right { 
      margin: 15mm 10mm 15mm 20mm; 
   }

   p, h2, h3 { 
      orphans: 3; widows: 3; 
   }

   h2, h3 { 
      page-break-after: avoid; 
   }
}

</style>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: rgb(88, 72, 246)
   }

   pre .number {
     color: rgb(0, 0, 205);
   }

   pre .comment {
     color: rgb(76, 136, 107);
   }

   pre .keyword {
     color: rgb(0, 0, 255);
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: rgb(3, 106, 7);
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>




</head>

<body>
<h1>Practical Machine Learning - Course Project</h1>

<h1></h1>

<h2>Methodology</h2>

<ol>
<li>Divide the training set into 3 sets - 60:20:20 (train, test, test2).<br/></li>
<li>Use training set for training different models - <strong>rpart, random forest, knn</strong> and <strong>svm</strong>.<br/></li>
<li>Predict and create ConfusionMatrix on <strong>test set</strong> to measure performance of models and tuning parameters.</li>
<li>For the best performing model in Step 3, use test2 set <strong>exactly once</strong> to compute Out Of Sample Error</li>
<li>Predict using the best performing model in Step 3, classification for 20 test samples. Create the submission files</li>
</ol>

<p>Tips: using foreach and doSNOW package to use 6 cores out of 8 cores on my windows computer</p>

<pre><code class="r">library(caret) 
</code></pre>

<pre><code>## Loading required package: lattice
## Loading required package: ggplot2
</code></pre>

<pre><code class="r">library(foreach)
library(doSNOW)
</code></pre>

<pre><code>## Loading required package: iterators
## Loading required package: snow
</code></pre>

<pre><code class="r">ncores &lt;- 6
set.seed(1234)
</code></pre>

<pre><code class="r"># load data
rawData &lt;- read.csv(&quot;pml-training.csv&quot;, na.strings=c(&quot;&quot;, &quot;NA&quot;, &quot;#DIV/0!&quot;))
# discard NAs
na.count &lt;- apply(rawData, 2, function(x) {sum(is.na(x))}) 
validData &lt;- rawData[, which(na.count == 0)]

# remove useless predictors
removeColumns &lt;- grep(&quot;timestamp|X|user_name|new_window|num_window&quot;, names(validData))
validData &lt;- validData[ ,-removeColumns]

# make training set 60
trainIndex     &lt;- createDataPartition(y = validData$classe, p=0.60, list=FALSE)
trainData      &lt;- validData[trainIndex, ]
nontrainData   &lt;- validData[-trainIndex, ]
# divide test data into test and validation (20:20)
testIndex  &lt;- createDataPartition(y = nontrainData$classe, p=0.50, list=FALSE)
testData   &lt;- nontrainData[testIndex, ]
testData2  &lt;- nontrainData[-testIndex, ]

classeColumnIndex &lt;- grep(&quot;classe&quot;, names(testData))
dim(trainData); dim(testData); dim(testData2)
</code></pre>

<pre><code>## [1] 11776    53
</code></pre>

<pre><code>## [1] 3923   53
</code></pre>

<pre><code>## [1] 3923   53
</code></pre>

<h1>Rpart model</h1>

<pre><code class="r"># run rpart model
system.time(
        model_rpart &lt;- train(classe ~ ., data = trainData, method=&quot;rpart&quot;)
        )
</code></pre>

<pre><code>## Loading required package: rpart
</code></pre>

<pre><code>##    user  system elapsed 
##   60.56    0.20   61.23
</code></pre>

<pre><code class="r">model_rpart
</code></pre>

<pre><code>## CART 
## 
## 11776 samples
##    52 predictors
##     5 classes: &#39;A&#39;, &#39;B&#39;, &#39;C&#39;, &#39;D&#39;, &#39;E&#39; 
## 
## No pre-processing
## Resampling: Bootstrapped (25 reps) 
## 
## Summary of sample sizes: 11776, 11776, 11776, 11776, 11776, 11776, ... 
## 
## Resampling results across tuning parameters:
## 
##   cp    Accuracy  Kappa  Accuracy SD  Kappa SD
##   0.04  0.5       0.4    0.03         0.04    
##   0.06  0.4       0.2    0.06         0.1     
##   0.1   0.3       0.07   0.04         0.06    
## 
## Accuracy was used to select the optimal model using  the largest value.
## The final value used for the model was cp = 0.04.
</code></pre>

<pre><code class="r">preds_rpart &lt;- predict(model_rpart, testData[, -classeColumnIndex])
</code></pre>

<pre><code>## Loading required package: rpart
</code></pre>

<pre><code class="r">confusionMatrix(preds_rpart, testData[, classeColumnIndex])
</code></pre>

<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1009  311  329  285  110
##          B   15  253   29  109  104
##          C   91  195  326  249  181
##          D    0    0    0    0    0
##          E    1    0    0    0  326
## 
## Overall Statistics
##                                         
##                Accuracy : 0.488         
##                  95% CI : (0.472, 0.504)
##     No Information Rate : 0.284         
##     P-Value [Acc &gt; NIR] : &lt;2e-16        
##                                         
##                   Kappa : 0.331         
##  Mcnemar&#39;s Test P-Value : NA            
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity             0.904   0.3333   0.4766    0.000   0.4521
## Specificity             0.631   0.9188   0.7789    1.000   0.9997
## Pos Pred Value          0.494   0.4961   0.3129      NaN   0.9969
## Neg Pred Value          0.943   0.8517   0.8757    0.836   0.8902
## Prevalence              0.284   0.1935   0.1744    0.164   0.1838
## Detection Rate          0.257   0.0645   0.0831    0.000   0.0831
## Detection Prevalence    0.521   0.1300   0.2656    0.000   0.0834
## Balanced Accuracy       0.768   0.6261   0.6278    0.500   0.7259
</code></pre>

<h3>Rpart model is not very accurate (only 50%).</h3>

<h1>Random Forest</h1>

<pre><code class="r"># power up cluster
cl &lt;- makeCluster(ncores)
registerDoSNOW(cl)

cv_opts &lt;- trainControl(method=&quot;cv&quot;, number=10, allowParallel=TRUE)

# run randomforest model
system.time(
        model_rf &lt;- train(classe ~ ., data = trainData, 
                method=&quot;rf&quot;, trControl = cv_opts)
        )
</code></pre>

<pre><code>## Loading required package: randomForest
## randomForest 4.6-7
## Type rfNews() to see new features/changes/bug fixes.
</code></pre>

<pre><code>##    user  system elapsed 
##   48.08    0.30  459.26
</code></pre>

<pre><code class="r"># stop cluster
stopCluster(cl)

model_rf
</code></pre>

<pre><code>## Random Forest 
## 
## 11776 samples
##    52 predictors
##     5 classes: &#39;A&#39;, &#39;B&#39;, &#39;C&#39;, &#39;D&#39;, &#39;E&#39; 
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## 
## Summary of sample sizes: 10599, 10600, 10598, 10598, 10599, 10598, ... 
## 
## Resampling results across tuning parameters:
## 
##   mtry  Accuracy  Kappa  Accuracy SD  Kappa SD
##   2     1         1      0.003        0.004   
##   30    1         1      0.002        0.003   
##   50    1         1      0.004        0.005   
## 
## Accuracy was used to select the optimal model using  the largest value.
## The final value used for the model was mtry = 27.
</code></pre>

<pre><code class="r">preds_rf &lt;- predict(model_rf, testData[, -classeColumnIndex])
</code></pre>

<pre><code>## Loading required package: randomForest
## randomForest 4.6-7
## Type rfNews() to see new features/changes/bug fixes.
</code></pre>

<pre><code class="r">confusionMatrix(preds_rf, testData[, classeColumnIndex])
</code></pre>

<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1116    7    0    0    0
##          B    0  750    5    0    4
##          C    0    2  675    9    1
##          D    0    0    4  632    3
##          E    0    0    0    2  713
## 
## Overall Statistics
##                                         
##                Accuracy : 0.991         
##                  95% CI : (0.987, 0.993)
##     No Information Rate : 0.284         
##     P-Value [Acc &gt; NIR] : &lt;2e-16        
##                                         
##                   Kappa : 0.988         
##  Mcnemar&#39;s Test P-Value : NA            
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity             1.000    0.988    0.987    0.983    0.989
## Specificity             0.998    0.997    0.996    0.998    0.999
## Pos Pred Value          0.994    0.988    0.983    0.989    0.997
## Neg Pred Value          1.000    0.997    0.997    0.997    0.998
## Prevalence              0.284    0.193    0.174    0.164    0.184
## Detection Rate          0.284    0.191    0.172    0.161    0.182
## Detection Prevalence    0.286    0.193    0.175    0.163    0.182
## Balanced Accuracy       0.999    0.993    0.992    0.990    0.994
</code></pre>

<h3>Random Forest is highly accurate (99.1%)</h3>

<h1>KNN Model</h1>

<pre><code class="r"># power up cluster
cl &lt;- makeCluster(ncores)
registerDoSNOW(cl) 

# run knn model
knn_opts &lt;- data.frame(.k=c(seq(3, 11, 2)))

system.time(
        model_knn &lt;- train(classe ~ ., data = trainData, 
                method=&quot;knn&quot;,  trControl = cv_opts, tuneGrid = knn_opts)
        )
</code></pre>

<pre><code>##    user  system elapsed 
##    0.78    0.10   54.41
</code></pre>

<pre><code class="r"># stop cluster
stopCluster(cl)

model_knn
</code></pre>

<pre><code>## k-Nearest Neighbors 
## 
## 11776 samples
##    52 predictors
##     5 classes: &#39;A&#39;, &#39;B&#39;, &#39;C&#39;, &#39;D&#39;, &#39;E&#39; 
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## 
## Summary of sample sizes: 10598, 10598, 10599, 10600, 10599, 10599, ... 
## 
## Resampling results across tuning parameters:
## 
##   k   Accuracy  Kappa  Accuracy SD  Kappa SD
##   3   0.9       0.9    0.008        0.01    
##   5   0.9       0.9    0.01         0.02    
##   7   0.9       0.8    0.01         0.02    
##   9   0.8       0.8    0.01         0.02    
##   10  0.8       0.8    0.01         0.01    
## 
## Accuracy was used to select the optimal model using  the largest value.
## The final value used for the model was k = 3.
</code></pre>

<pre><code class="r">preds_knn &lt;- predict(model_knn, testData[, -classeColumnIndex])
confusionMatrix(preds_knn, testData[, classeColumnIndex])
</code></pre>

<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1086   26    5    8    7
##          B    4  673   19    3   25
##          C    6   25  630   32   17
##          D   15   19   20  594   17
##          E    5   16   10    6  655
## 
## Overall Statistics
##                                         
##                Accuracy : 0.927         
##                  95% CI : (0.919, 0.935)
##     No Information Rate : 0.284         
##     P-Value [Acc &gt; NIR] : &lt; 2e-16       
##                                         
##                   Kappa : 0.908         
##  Mcnemar&#39;s Test P-Value : 5.05e-06      
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity             0.973    0.887    0.921    0.924    0.908
## Specificity             0.984    0.984    0.975    0.978    0.988
## Pos Pred Value          0.959    0.930    0.887    0.893    0.947
## Neg Pred Value          0.989    0.973    0.983    0.985    0.980
## Prevalence              0.284    0.193    0.174    0.164    0.184
## Detection Rate          0.277    0.172    0.161    0.151    0.167
## Detection Prevalence    0.289    0.185    0.181    0.170    0.176
## Balanced Accuracy       0.978    0.935    0.948    0.951    0.948
</code></pre>

<h3>KNN is about 92.7% accurate, which is quite good and this was much faster to train than random forest.</h3>

<h1>SVM model</h1>

<pre><code class="r"># power up cluster
cl &lt;- makeCluster(ncores)
registerDoSNOW(cl)

# run knn model

system.time(
        model_svm &lt;- train(classe ~ ., data = trainData, 
                method=&quot;svmLinear&quot;,  trControl = cv_opts, tuneLength = 5)
        )
</code></pre>

<pre><code>## Loading required package: kernlab
</code></pre>

<pre><code>##    user  system elapsed 
##   15.57    0.33   75.76
</code></pre>

<pre><code class="r"># stop cluster
stopCluster(cl)

model_svm
</code></pre>

<pre><code>## Support Vector Machines with Linear Kernel 
## 
## 11776 samples
##    52 predictors
##     5 classes: &#39;A&#39;, &#39;B&#39;, &#39;C&#39;, &#39;D&#39;, &#39;E&#39; 
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## 
## Summary of sample sizes: 10597, 10598, 10598, 10598, 10600, 10599, ... 
## 
## Resampling results
## 
##   Accuracy  Kappa  Accuracy SD  Kappa SD
##   0.8       0.7    0.02         0.02    
## 
## Tuning parameter &#39;C&#39; was held constant at a value of 1
## 
</code></pre>

<pre><code class="r">preds_svm &lt;- predict(model_svm, testData[, -classeColumnIndex])
</code></pre>

<pre><code>## Loading required package: kernlab
</code></pre>

<pre><code class="r">confusionMatrix(preds_svm, testData[, classeColumnIndex])
</code></pre>

<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1046  100   75   48   30
##          B   14  548   64   32  101
##          C   30   48  516   71   51
##          D   24    8   19  454   38
##          E    2   55   10   38  501
## 
## Overall Statistics
##                                         
##                Accuracy : 0.781         
##                  95% CI : (0.768, 0.794)
##     No Information Rate : 0.284         
##     P-Value [Acc &gt; NIR] : &lt;2e-16        
##                                         
##                   Kappa : 0.722         
##  Mcnemar&#39;s Test P-Value : &lt;2e-16        
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity             0.937    0.722    0.754    0.706    0.695
## Specificity             0.910    0.933    0.938    0.973    0.967
## Pos Pred Value          0.805    0.722    0.721    0.836    0.827
## Neg Pred Value          0.973    0.933    0.948    0.944    0.934
## Prevalence              0.284    0.193    0.174    0.164    0.184
## Detection Rate          0.267    0.140    0.132    0.116    0.128
## Detection Prevalence    0.331    0.193    0.183    0.138    0.154
## Balanced Accuracy       0.924    0.828    0.846    0.839    0.831
</code></pre>

<h3>SVM was only 78.1% accurate. Which is not as good as others.</h3>

<h1>Results</h1>

<h3>We have the best prediction from Random Forest, so we select Random Forest as our final model.</h3>

<h3>First we calculate out of sample error on testData2 (which was havent used till now)</h3>

<pre><code class="r">oos_rf &lt;- predict(model_rf, testData2[, -classeColumnIndex])
confusionMatrix(oos_rf, testData2[, classeColumnIndex])
</code></pre>

<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1116   11    0    0    0
##          B    0  744    9    1    0
##          C    0    4  671   11    1
##          D    0    0    4  631    1
##          E    0    0    0    0  719
## 
## Overall Statistics
##                                         
##                Accuracy : 0.989         
##                  95% CI : (0.986, 0.992)
##     No Information Rate : 0.284         
##     P-Value [Acc &gt; NIR] : &lt;2e-16        
##                                         
##                   Kappa : 0.986         
##  Mcnemar&#39;s Test P-Value : NA            
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity             1.000    0.980    0.981    0.981    0.997
## Specificity             0.996    0.997    0.995    0.998    1.000
## Pos Pred Value          0.990    0.987    0.977    0.992    1.000
## Neg Pred Value          1.000    0.995    0.996    0.996    0.999
## Prevalence              0.284    0.193    0.174    0.164    0.184
## Detection Rate          0.284    0.190    0.171    0.161    0.183
## Detection Prevalence    0.287    0.192    0.175    0.162    0.183
## Balanced Accuracy       0.998    0.989    0.988    0.990    0.999
</code></pre>

<h3>Accuracy is 0.989.</h3>

<h3>Out of Sample Error is 0.011.</h3>

<h3>95% CI is (0.008 to 0.014).</h3>

<h1>Predicting outcome on given 20 test cases</h1>

<pre><code class="r"># Predict the outcomes in the given test file
classetestData &lt;- read.csv(&quot;pml-testing.csv&quot;, na.strings=c(&quot;&quot;, &quot;NA&quot;, &quot;#DIV/0!&quot;))
removeColumns &lt;- grep(&quot;timestamp|X|user_name|new_window|num_window&quot;, names(classetestData))
classetestData &lt;- classetestData[ ,-removeColumns]
answers &lt;- predict(model_rf, classetestData)
answers
</code></pre>

<pre><code>##  [1] B A B A A E D B A A B C B A E E A B B B
## Levels: A B C D E
</code></pre>

<pre><code class="r"># write output to files

pml_write_files &lt;- function(answers){
        x &lt;- as.character(answers)
        n = length(x)
        for(i in 1:n){
                filename = paste0(&quot;problem_id_&quot;,i,&quot;.txt&quot;)
                write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
        }
}

pml_write_files(answers)
</code></pre>

</body>

</html>

